language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  # Download the latest version of pandoc
  - python -c "from pypandoc.pandoc_download import download_pandoc; download_pandoc()"
script: make publish
deploy:
  local-dir: output  # Defined in the Makefile
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
