language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
deploy:
  local-dir: output  # Defined in the Makefile
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
