language: python
python:
  - '3.6'
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.3.2-1-amd64.deb
install:
  - pip install -r requirements.txt
script: make publish
deploy:
  local-dir: output  # Defined in the Makefile
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
